---
title: "QI Report"
author: "Your Name"
date: "`r Sys.Date()`"
output: html_document
---

# QI Report

This report uses the **qiTools** package to analyze and visualize quality improvement data.

---

## 📦 Load Libraries


```{r}
library(qiTools)
library(dplyr)
library(ggplot2)
```

```{r}
annotations <- data.frame(
  Date = as.Date(c("2024-09-01", "2025-02-15")),
  Label = c("Go Live", "Townhall"),
  Side = c("right", "left")
)

summary <- qi_spc(
  df,
  date_col = "Incident Date",
  id_col = "pcr",
  num_condition = "hr > 100",
  den_condition = "TRUE",
  time_unit = "week",
  name = "High Heart Rate Cases",
  annotations = annotations
)
```

```{r}
save_qi_spc(path = ".", width = 18, height = 6, save_table = TRUE)
```

```{r}
table <- qi_table(
  df,
  date_col = "Incident Date",
  id_col = "pcr",
  num_condition = "hr > 100",
  den_condition = "TRUE",
  time_unit = "week"
)
print(table)

```

```{r}
check_missing(df)
check_duplicates(df)
check_outliers(df)
describe_data(df)

```

```{r}
profile_data(df)
```

